<?php

add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_6949d3b9cbe77',
		'title' => 'Hero slide fields',
		'fields' => array(
			array(
				'key' => 'field_6949d3bb0f353',
				'label' => 'Page URL',
				'name' => 'page_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'hero-slide',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	));
});

add_action('init', function () {
	register_post_type('global-alerts', array(
		'labels' => array(
			'name' => 'Global alerts',
			'singular_name' => 'Global alert',
			'menu_name' => 'Global alerts',
			'all_items' => 'All Global alerts',
			'edit_item' => 'Edit Global alert',
			'view_item' => 'View Global alert',
			'view_items' => 'View Global alerts',
			'add_new_item' => 'Add New Global alert',
			'add_new' => 'Add New Global alert',
			'new_item' => 'New Global alert',
			'parent_item_colon' => 'Parent Global alert:',
			'search_items' => 'Search Global alerts',
			'not_found' => 'No global alerts found',
			'not_found_in_trash' => 'No global alerts found in Trash',
			'archives' => 'Global alert Archives',
			'attributes' => 'Global alert Attributes',
			'insert_into_item' => 'Insert into global alert',
			'uploaded_to_this_item' => 'Uploaded to this global alert',
			'filter_items_list' => 'Filter global alerts list',
			'filter_by_date' => 'Filter global alerts by date',
			'items_list_navigation' => 'Global alerts list navigation',
			'items_list' => 'Global alerts list',
			'item_published' => 'Global alert published.',
			'item_published_privately' => 'Global alert published privately.',
			'item_reverted_to_draft' => 'Global alert reverted to draft.',
			'item_scheduled' => 'Global alert scheduled.',
			'item_updated' => 'Global alert updated.',
			'item_link' => 'Global alert Link',
			'item_link_description' => 'A link to a global alert.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
			3 => 'custom-fields',
		),
		'delete_with_user' => false,
	));

	register_post_type('hero-slide', array(
		'labels' => array(
			'name' => 'Hero slides',
			'singular_name' => 'Hero slide',
			'menu_name' => 'Hero slides',
			'all_items' => 'All Hero slides',
			'edit_item' => 'Edit Hero slide',
			'view_item' => 'View Hero slide',
			'view_items' => 'View Hero slides',
			'add_new_item' => 'Add New Hero slide',
			'add_new' => 'Add New Hero slide',
			'new_item' => 'New Hero slide',
			'parent_item_colon' => 'Parent Hero slide:',
			'search_items' => 'Search Hero slides',
			'not_found' => 'No hero slides found',
			'not_found_in_trash' => 'No hero slides found in Trash',
			'archives' => 'Hero slide Archives',
			'attributes' => 'Hero slide Attributes',
			'insert_into_item' => 'Insert into hero slide',
			'uploaded_to_this_item' => 'Uploaded to this hero slide',
			'filter_items_list' => 'Filter hero slides list',
			'filter_by_date' => 'Filter hero slides by date',
			'items_list_navigation' => 'Hero slides list navigation',
			'items_list' => 'Hero slides list',
			'item_published' => 'Hero slide published.',
			'item_published_privately' => 'Hero slide published privately.',
			'item_reverted_to_draft' => 'Hero slide reverted to draft.',
			'item_scheduled' => 'Hero slide scheduled.',
			'item_updated' => 'Hero slide updated.',
			'item_link' => 'Hero slide Link',
			'item_link_description' => 'A link to a hero slide.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
			3 => 'custom-fields',
		),
		'delete_with_user' => false,
	}));

	add_action('init', function () {
		register_taxonomy('display-location', array(
			0 => 'testimonial',
			1 => 'team-member',
			2 => 'page',
		), array(
			'labels' => array(
				'name' => 'Display locations',
				'singular_name' => 'Display location',
				'menu_name' => 'Display locations',
				'all_items' => 'All Display locations',
				'edit_item' => 'Edit Display location',
				'view_item' => 'View Display location',
				'update_item' => 'Update Display location',
				'add_new_item' => 'Add New Display location',
				'new_item_name' => 'New Display location Name',
				'search_items' => 'Search Display locations',
				'popular_items' => 'Popular Display locations',
				'separate_items_with_commas' => 'Separate display locations with commas',
				'add_or_remove_items' => 'Add or remove display locations',
				'choose_from_most_used' => 'Choose from the most used display locations',
				'not_found' => 'No display locations found',
				'no_terms' => 'No display locations',
				'items_list_navigation' => 'Display locations list navigation',
				'items_list' => 'Display locations list',
				'back_to_items' => '← Go to display locations',
				'item_link' => 'Display location Link',
				'item_link_description' => 'A link to a display location',
			),
			'public' => true,
			'show_in_menu' => true,
			'show_in_rest' => true,
		));
	});

	register_post_type('testimonial', array(
		'labels' => array(
			'name' => 'Testimonials',
			'singular_name' => 'Testimonial',
			'menu_name' => 'Testimonials',
			'all_items' => 'All testimonials',
			'edit_item' => 'Edit testimonial',
			'view_item' => 'View testimonial',
			'view_items' => 'View testimonials',
			'add_new_item' => 'Add New testimonial',
			'add_new' => 'Add New testimonial',
			'new_item' => 'New testimonial',
			'parent_item_colon' => 'Parent testimonial:',
			'search_items' => 'Search testimonials',
			'not_found' => 'No testimonials found',
			'not_found_in_trash' => 'No testimonials found in Trash',
			'archives' => 'Testimonial Archives',
			'attributes' => 'Testimonial Attributes',
			'insert_into_item' => 'Insert into testimonial',
			'uploaded_to_this_item' => 'Uploaded to this testimonial',
			'filter_items_list' => 'Filter testimonials list',
			'filter_by_date' => 'Filter testimonials by date',
			'items_list_navigation' => 'Testimonials list navigation',
			'items_list' => 'Testimonials list',
			'item_published' => 'Testimonial published.',
			'item_published_privately' => 'Testimonial published privately.',
			'item_reverted_to_draft' => 'Testimonial reverted to draft.',
			'item_scheduled' => 'Testimonial scheduled.',
			'item_updated' => 'Testimonial updated.',
			'item_link' => 'Testimonial Link',
			'item_link_description' => 'A link to a testimonial.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
			3 => 'custom-fields',
		),
		'taxonomies' => array(
			0 => 'career-testimonial',
			1 => 'business-testimonial',
			2 => 'front-page-testimonial',
		),
		'delete_with_user' => false,
	));
});
